// <auto-generated />
namespace CrudWith_DpMigration_Postgresql.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class contexttable140420202at0152pm : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(contexttable140420202at0152pm));
        
        string IMigrationMetadata.Id
        {
            get { return "202004140823057_contexttable140420202at0152pm"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
